ciphertext = "ITKHRABBPTHORGPTUBIWCBKQHGIGITVTBKQPBIHOTPVHIBOMCBKQPTORITPTTWTKETVTJHPBIOBKLBPHRGVCBPQHLBAHYTOAGMBLTOOGICKQBPKTJTPJTLBTVTRHKGKTIGELBVCIJPHUBRQTKLHOHMVPTOQBMVIHPHOTOTOGTIPBLBLHPBIVHOZGBJTPBRCTBOQPBRATPOBRHKRTLTJTOHUBITCPBOBWHIWCTMTOLBKOHRTPDTLHLBGKTPHMTQBPPHOHUTKQCDGHTIHIBYHOGKTOCIGBQTLCFGOTTJTPBRCHBKQPBITKBVICKTGKMHWCMCBKQHRTOCCMJBPRBJQCVIBZGBACEHZGBOGRHPTEHKOBTRBIBPTPTOCDGCHTWTKETKLHRHKRTGQBITOCKQCBKLHZGBRTLTOHKCLHLBIVHOZGBPBOHKTVTLBMTOCTLHFGBPQBLBKQPHLBOGRTVBETGKRPGYCLHTOGCEZGCBPLTHQPHTOGLBPBRATOGPBOJCPTRCHKOBWHIWCHJBOTLTMCBKQPTOCKQBKQTVTRHKWBKRBPOBLBZGBOHIHBPTKPTMTOTDCQTLTOJHPBIWCBKQHBIOBKLBPHOBQHPKHMTOBOQPBRAHUITWBDBQTRCHKJTPBRCTRBPPTPOBRHMHOCCKQBKQTPTTQPTJTPITITICKQBPKTQCQCIHGKTWBEMTOTKQBOLBTJTDTPOBJHPRHMJIBQHLBYTKLHITOGMCLTBKITJBKGMVPTOCKQCHGKBORTIHFPCHPBRHPPBPOGBOJTILTUOGJHZGBKHBOQTVTOHITGKOGOGPPHCMJBPRBJQCVIBPHEHOGOHCLHOUBKBOBCKOQTKQBRHMJPBKLCHZGBUTKHQBKCTBORTJTQHPCT"

substitutions = {
    'T': 'A', 
    'B': 'E', 
    'H': 'O', 
    'O': 'S', 
    'P': 'R', 
    'K': 'N', 
    'C': 'I', 
    'I': 'L',
    'G':'U'
    
}

decoded_text = "".join(substitutions.get(char, char) for char in ciphertext)
print(decoded_text)