texto_cifrado = "NLDIXALALNLSLZMNBKLDLAPIMAHIMFXKUHILAJLFXULDLSKAJLNEMAMDIKNLLIKULRPFKSLKNFLIAKKVHKUSXLLUHKKNJMFMPUFLUHMMAJPIMCIPZXKUHKJLSLMNLSKGLDLPUILAHIMKABPFMAMLUHKASKIKHXILIAKSKOMILUSMNLMIXNNLBMJMLBMJMAKUHXLKNQIXMAPDXIBMIAPABXKIULABKIMUMAKSKHKUXLAPABLAMAKILUNKUHMABKALSMAJMFMAXLNZMXUOXAXDNKHXILILSKKNRLJXLKNRMIXEMUHKXUQXUXHMLNMNKGMAPULNPESKDXNBLIBLSKLDLKUKNLZPLQNMHLUSMAXUFMOKIAKLBKALISKNMNKLGKXUHKUHMXZUMILINLBKIMLNZMSKUHIMSKKNNMMDNXZLDLLLJKIJLIAKKNNLHXSMSKAPJMILEMUAKOMNOXMXIIKZPNLIFXKUHILAKNLZPLNKJPDIXLNLAIMSXNNLANPKZMNLJXUHPILNLIKABXILJXMUAKKUHIKJMIHMJPLUSMKNQIXMNKNNKZMLNBKJRMBKIMAXZPXMLOLUELUSMXUJLBLESKIKAXAHXIAKJLSLOKEFLAJKIJLJLSLOKEFLABIMQPUSMJPLUSMKAHPOMLPUBLAMSKNLNPEKVHKUSXMNLFLUMCKUKAKXUAHLUHKNLOXMPUMAMGMAAXUDIXNNMKFKIZXKIMUSKNLAAMFDILADLGMKNLZPLPUIMAHIMBLNXSMCLGLSMNMMDAKIOLDLSKASKNLABIMQPUSXSLSKAAXUHXMPUHXIMUKUNMAHMDXNNMACLUHKASKTPKBPSXKILZIXHLIKNFLINMSKOMIMAXUSKGLIILAHIMAMNMNLNPETPKSMQNMHLUSMKABKILUSMLMHIMOXLGKIMAMNXHLIXM"

sustituciones = {
    'L': 'A', #BIEN
    'M': 'O', #BIEN
    'K': 'E', #BIEN
    'I': 'R',
    'A': 'S', #BIEN
    'N': 'L',
    #'X': 'I'
}

# Crear el texto descifrado
texto_descifrado = "".join(sustituciones.get(char, char) for char in texto_cifrado)


print(texto_descifrado)
